HOST lewis.lbl.gov
only_i 36
only_code None
force_amber_prep True
dry_run False
1 1z3z,A,2.900,1zod,A,1.800
2 1psi,A,2.920,3ndd,A,1.500
3 3bpo,A,3.000,3l5w,I,2.000
4 1e6j,P,3.000,3mge,A,1.900
5 1r46,A,3.250,3hg3,A,1.900
6 2j0g,A,2.850,2j1g,A,1.950
7 1nsk,L,2.800,3bbb,A,1.300
8 1t04,B,3.000,1t3f,B,2.000
9 1kiu,B,3.000,1ze3,H,1.840
10 1kv3,A,2.800,2q3z,A,2.000
11 1wqs,A,2.800,2iph,A,1.750
12 3gwp,A,2.900,3i16,A,2.000
13 1c0n,A,2.800,1kmj,A,2.000
14 2r8j,A,3.100,3oha,A,2.000
15 1z5s,C,3.010,2grn,B,1.800
16 3icq,B,3.200,3m1i,A,2.000
17 1nb3,I,2.800,3kfq,C,1.990
18 1otc,A,2.800,2i0q,A,1.910
... 36 2i0q
/net/chevy/raid1/nigel/amber/hi_lo
/net/chevy/raid1/nigel/amber/hi_lo/i0/2i0q
2i0q.pdb 4phenix_2i0q.pdb
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/i0/pdb2i0q.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/i0/2i0q/2i0q.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/i0/pdb2i0q.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/i0/2i0q/2i0q.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

==================================================
Summary of pdb4amber for: 2i0q.pdb
===================================================
REDUCE returned non-zero exit status: See reduce_info.log for more details

----------Chains
The following (original) chains have been found:
A
B
D

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
SER_25
ALA_26
GLN_27
PRO_28
GLN_29
ASN_45
GLN_46
TYR_119
SER_120
ASP_145
THR_146
GLU_212
LEU_213
GLU_246
VAL_247
ILE_274
THR_275
GLN_328
ASP_329
THR_405
TYR_406
LEU_481
TYR_482
SER_497
ASN_498
THR_596
ARG_597
HOH_816
HOH_845
HOH_994

---------- Mising heavy atom(s)

GLU_47 misses 4 heavy atom(s)
ARG_48 misses 5 heavy atom(s)
GLN_64 misses 4 heavy atom(s)
LYS_66 misses 4 heavy atom(s)
LYS_82 misses 2 heavy atom(s)
LYS_130 misses 4 heavy atom(s)
LYS_160 misses 4 heavy atom(s)
GLN_167 misses 2 heavy atom(s)
LYS_171 misses 3 heavy atom(s)
LYS_198 misses 3 heavy atom(s)
LYS_284 misses 3 heavy atom(s)
LYS_303 misses 2 heavy atom(s)
LYS_317 misses 3 heavy atom(s)
GLU_339 misses 4 heavy atom(s)
GLN_343 misses 4 heavy atom(s)
LYS_370 misses 4 heavy atom(s)
LYS_373 misses 4 heavy atom(s)
LYS_383 misses 4 heavy atom(s)
GLU_443 misses 3 heavy atom(s)
GLN_473 misses 4 heavy atom(s)
LYS_501 misses 3 heavy atom(s)
LYS_504 misses 2 heavy atom(s)
LYS_529 misses 4 heavy atom(s)
LYS_538 misses 4 heavy atom(s)
ASN_541 misses 3 heavy atom(s)
LYS_550 misses 3 heavy atom(s)
GLU_568 misses 2 heavy atom(s)
LYS_586 misses 3 heavy atom(s)
GLN_590 misses 4 heavy atom(s)
LYS_626 misses 2 heavy atom(s)
LYS_629 misses 3 heavy atom(s)
LYS_660 misses 4 heavy atom(s)
LYS_670 misses 4 heavy atom(s)
LYS_687 misses 3 heavy atom(s)
The alternate coordinates have been discarded.
Only the first occurrence for each atom was kept.
not prmtop_filename /net/lewis/scratch1/nigel/amber/hi_lo/i0/2i0q/4amber_2i0q.prmtop
not prmtop_filename /net/chevy/raid1/nigel/amber/hi_lo/i0/2i0q/4amber_2i0q.prmtop

	Running AmberPrep : 2i0q.pdb


==================================================
Running pdb4amber on 2i0q.pdb
==================================================

==================================================
Setting up library files for non-standard residues
==================================================

==================================================
Running elbow/antechamber for DG 
==================================================
Traceback (most recent call last):
  File "run_tests_local.py", line 321, in <module>
    run(*tuple(args))
  File "run_tests_local.py", line 305, in run
    w2 = run_all_tests(code, force_amber_prep=force_amber_prep)
  File "run_tests_local.py", line 93, in run_all_tests
    "clean=on",
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 961, in run
    prefer_input_method=inputs.antechamber.prefer_input_method,
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 393, in process_ligands
    _run_elbow_antechamber(self.pdb_hierarchy, residue_name, debug=debug)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 877, in _run_elbow_antechamber
    pdb_mol.Bondise(add_bond_order=False)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/elbow/elbow/chemistry/BondTopologyMixins.py", line 161, in Bondise
    self.CheckBondise(keep_all_atoms=keep_all_atoms)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/elbow/elbow/chemistry/BondTopologyMixins.py", line 871, in CheckBondise
    bonded = self._get_bonded_to_atom()
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/elbow/elbow/chemistry/BondTopologyMixins.py", line 786, in _get_bonded_to_atom
    bonded = [self[i].index]
IndexError: list index out of range
