HOST lewis.lbl.gov
only_i 52
only_code None
force_amber_prep True
dry_run False
1 1z3z,A,2.900,1zod,A,1.800
2 1psi,A,2.920,3ndd,A,1.500
3 3bpo,A,3.000,3l5w,I,2.000
4 1e6j,P,3.000,3mge,A,1.900
5 1r46,A,3.250,3hg3,A,1.900
6 2j0g,A,2.850,2j1g,A,1.950
7 1nsk,L,2.800,3bbb,A,1.300
8 1t04,B,3.000,1t3f,B,2.000
9 1kiu,B,3.000,1ze3,H,1.840
10 1kv3,A,2.800,2q3z,A,2.000
11 1wqs,A,2.800,2iph,A,1.750
12 3gwp,A,2.900,3i16,A,2.000
13 1c0n,A,2.800,1kmj,A,2.000
14 2r8j,A,3.100,3oha,A,2.000
15 1z5s,C,3.010,2grn,B,1.800
16 3icq,B,3.200,3m1i,A,2.000
17 1nb3,I,2.800,3kfq,C,1.990
18 1otc,A,2.800,2i0q,A,1.910
19 1ue8,A,3.000,3b4x,A,1.940
20 1a4o,A,2.800,2o02,A,1.500
21 1t6i,A,2.810,3g4z,A,1.870
22 1de9,A,3.000,2o3h,A,1.900
23 2j6e,L,3.000,3n9g,L,1.434
24 3hrk,A,3.050,3lc0,A,1.800
25 2ecp,A,2.950,2asv,A,1.950
26 1z8l,A,3.500,2xeg,A,1.590
... 52 2xeg
/net/chevy/raid1/nigel/amber/hi_lo
/net/chevy/raid1/nigel/amber/hi_lo/xe/2xeg
2xeg.pdb 4phenix_2xeg.pdb
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/xe/pdb2xeg.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/xe/2xeg/2xeg.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/xe/pdb2xeg.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/xe/2xeg/2xeg.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

==================================================
Summary of pdb4amber for: 2xeg.pdb
===================================================
REDUCE returned non-zero exit status: See reduce_info.log for more details

----------Chains
The following (original) chains have been found:
A

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
MET_4
PHE_36
ILE_42
SER_44
GLU_48
SER_53
SER_88
LEU_120
VAL_185
GLU_222
TYR_223
TYR_225
ARG_226
SER_237
MET_255
SER_347
THR_350
LEU_351
LEU_374
LEU_375
GLN_389
GLU_390
ARG_409
SER_418
MET_455
LYS_460
SER_500
MET_515
PHE_516
GLU_532
LEU_533
ASN_535
SER_536
ILE_537
LYS_556
SER_559
GLN_566
SER_572
LYS_591
SER_593
SER_600
ASN_601
PRO_602
ILE_603
VAL_604
LEU_605
ARG_606
MET_607
MET_608
ARG_632
SER_640
SER_661
LYS_673
not prmtop_filename /net/lewis/scratch1/nigel/amber/hi_lo/xe/2xeg/4amber_2xeg.prmtop
not prmtop_filename /net/chevy/raid1/nigel/amber/hi_lo/xe/2xeg/4amber_2xeg.prmtop

	Running AmberPrep : 2xeg.pdb


==================================================
Running pdb4amber on 2xeg.pdb
==================================================
Traceback (most recent call last):
  File "run_tests_local.py", line 321, in <module>
    run(*tuple(args))
  File "run_tests_local.py", line 305, in run
    w2 = run_all_tests(code, force_amber_prep=force_amber_prep)
  File "run_tests_local.py", line 93, in run_all_tests
    "clean=on",
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 951, in run
    arg_conect=False,
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber/lib/python2.7/site-packages/pdb4amber/pdb4amber.py", line 522, in run
    gaplist = pdbfixer.find_gaps()
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber/lib/python2.7/site-packages/pdb4amber/pdb4amber.py", line 213, in find_gaps
    N_atom = parm.atoms[N_atoms[i + 1]]
IndexError: list index out of range
